package com.intuit.craft.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.intuit.craft.dto.ValidationTaskSubStatus;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "ProfileValidationSubTaskTable")
public class ProfileValidationSubTask {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String parentTaskId;

    @DynamoDBAttribute
    private String serviceId;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private ValidationTaskSubStatus status;

    @DynamoDBAttribute
    private String reason;

}
