package com.intuit.craft.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.intuit.craft.dto.ValidationTaskStatus;
import lombok.Data;

import java.util.Date;

@Data
@DynamoDBTable(tableName = "ProfileValidationTaskTable")
public class ProfileValidationTask {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String profileId;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private ValidationTaskStatus status;

    @DynamoDBAttribute
    private String profileRequest;

    @DynamoDBAttribute
    private Integer retryCount;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdDate;

}
